### ISSUE TITLE
Gameplay loop - healing and returning to town

### ISSUE THREAD

**Issue by CannonFodder2** [tgruby/dungeon-hunt#11]
As is stands, the most cost-efficient way to get healed seems to be to return to town and go to the temple. There's no cost or risk to doing this, because you can retrace your steps with no danger to you. But it creates a tedious gameplay loop in an otherwise fast-paced game - on floor 2, get hit hard by a vampire bat - turn around, navigate through floor 1, then through floor 0, heal at temple, then back to floor 0, floor 1, floor 2, repeat. Takes a couple of minutes of just retracing steps. 

This also means I never use potions. 

I think you should de-incentivize this gameplay loop to keep the pace-of-play moving forward. A couple of ways you can do it - 1) remove the Temple entirely, forcing the player to stock up on potions, and/or (2 when entering the dungeon, allow the user to teleport past levels he has already cleared. Similarly, when ascending a level, allow the user to teleport right back to town. Perhaps this is an ability that you can unlock by buying maps.

**Comment by tgruby** [comment]
wonder if we should also have randomly wandering monsters.  That way it would create a larger incentive to use potions and teleport.

**Comment by tgruby** [comment]
As I think about this more, the best thing would be to skip the level once cleared.  I think that mean if you find all monsters and open all chests when you enter and exit the dungeon you will go directly to the fist uncleared dungeon.

**Comment by R2Dead2** [comment]
Another way to go about is the "Rest" mechanism.  Remove the temple and add a Camp or Inn.  The player then has the option to rest and regain hit points.  At the same time, monsters respawn in the dungeon.  The player could save money by resting at the camp but doesn't fully heal or pay more for a room at the "Inn of Weary Feet" but fully heal.  
This does change gameplay alittle.  You could farm lvl 0 until you get enough gold for all the best stuff.

**Comment by R2Dead2** [comment]
There could also be a portal in town that allows you to return to a "Portal Room" that you've discovered on each floor.

**Comment by CannonFodder2** [comment]
Having played the new version, here are my thoughts on this issue: 

As it stands, the game feels MUCH harder than before. This is because we need to spend a lot more money healing ourselves. And unfortunately, I'm still running back to town each time I need to heal. This is because I can't afford to buy extra potions to extend runs - and I want to save as much money as I can for equipment. So maybe my idea of removing the temple wasn't such a good one. 

I'm trying to think of a good way to solve this problem by thinking of other roguelike games I've played. Admittedly, it's a limited dataset. But in every case, there's one common variable: you NEVER go back. The player must always push forward, keeping the momentum and pace of play up. So, in the games I've played, you often have one-off opportunities to heal ALONG THE WAY. For example, after completing a level, you can heal a certain percentage of HP. Or, if you purchase a specific item, you heal 2HP after defeating each enemy. Or a combination of items that heal you each time you attack. Similarly, you encounter merchants ALONG THE WAY - but you can never, ever go backwards.

**Comment by tgruby** [comment]
I thought so too. I’ll add skipping the level once complete. Also hide a
potion of healing in a chest per level, add back the temple. Not quite sure
about never going back to the town given the core of the game is the maze.

I think another problem is the toughness balance between the easy and hard
monsters.  They seem too hard. I’ll try and weaken the stronger monsters.

**Comment by tgruby** [comment]
Ok, I have added "skipping the level" once you have completed it.  I also have done some rebalancing of monster's abilities, and added the temple back in.
