### ISSUE TITLE
A use for loot

### ISSUE THREAD

**Issue by CannonFodder2** [tgruby/dungeon-hunt#12]
Unless I'm missing something, it seems like the only use for loot (gnome's feet, bat wings, that kind of thing) is to sell it at the potion shop. It might be cool if it had a greater purpose - if, for example, the potion maker had a set of unique potions available that _require_ one of those ingredients for purchase. So, to get the Potion of Gnomic Swiftness, which gives you a 50% dodge chance, you have to pay gold and a gnome foot. This would make getting the loot items more exciting, and also add some extra randomness to the runs.

**Comment by tgruby** [comment]
I like it.  In general, I think there should be potions of strength (+attack damage), agility (avoid damage or reduce damage), and teleport (to quickly get back to the town).  Lets think about making the potion shop less gold for potions, but you have to bring the right loot as well.

**Comment by tgruby** [comment]
ok, changed the gameplay to "buy potions with monster parts".  Will need to work on making it more complex (and adding more potions).

**Comment by tgruby** [comment]
Gonna resolve this.
