### ISSUE TITLE
Add a Guild

### ISSUE THREAD

**Issue by tgruby** [tgruby/dungeon-hunt#14]
Consider adding a guild where gamers could leave messages for each other, possibly even trade/sell items.  This might be especially interesting if there are magical items that are only found in the dungeon, you cannot buy them in the town.

**Comment by R2Dead2** [comment]
I do not like the idea of being able to buy magical items.  Finding them while adventuring is always more gratifying and makes even the lowest lvl magical items awesome.

**Comment by tgruby** [comment]
ok, sounds good.  will close this item.
