### ISSUE TITLE
Make Maps Appear in Chests

### ISSUE THREAD

**Issue by CannonFodder2** [tgruby/dungeon-hunt#15]
I think the "exploring without a map," and then "oh, I got the map and THAT's what this level looks like!" parts of this game are the strongest features of the game. It's fun, and a relief, to suddenly see the layout of the map you were wandering through before. However, I suggest that you nix the cartographer and make the map for each level a random treasure chest IN that level. That forces the player to blindly explore a bit until they find the requisite treasure. It also means the player doesn't feel pressured to spend precious money on a map (This is important, because the map is, technically, a convenience, and a player playing to maximize score will avoid getting them as long as possible and buy equipment instead.)

**Comment by tgruby** [comment]
Good call.  I am trying a twist on this, but open to going back to this suggestion and putting maps in chests (I did this, and then took them back out for the potion idea).  The twist is to have a potion that gives the player clairvoyance for a period of time (currently 50 steps).  potions have been moved to being purchased with monster parts.

**Comment by tgruby** [comment]
done
