### ISSUE TITLE
add more descriptions for shields, armor, weapons, potions

### ISSUE THREAD

**Issue by tgruby** [tgruby/dungeon-hunt#4]
At times individuals have mentioned they don't know what a heater or buckler is (shields).  Should be displayable in shops and inventory.

**Comment by R2Dead2** [comment]
Possibly add a "Are you sure you want to buy this?" that has a picture and brief description.

**Comment by tgruby** [comment]
That’s a frocking lot of work for a guy who has no graphics ability. You offering? :)

**Comment by tgruby** [comment]
Now that I have moved the game to the web, it wouldn’t be hard to interweave images into the system. Do you draw or can you produce pictures?

**Comment by R2Dead2** [comment]
I can give it a try. I have zero experience though.  My first thought was to steal them from the D&D Beyond website, but I'm also thinking that it may be a bad idea due to copyrights.  Mostly just scared of lawyers though.

**Comment by tgruby** [comment]
:) yep, me too scared of lawyers. That part can wait, too. I was thinking
of adding more magical items in the dungeon, maybe get one every level.
Thoughts on that.  Pretty sure a ring of protection is needed...

**Comment by tgruby** [comment]
Going to close this off for now.  Wait for more complaints 👍
