### ISSUE TITLE
Lock the doors between levels, have a key hidden in each level.

### ISSUE THREAD

**Issue by R2Dead2** [tgruby/dungeon-hunt#9]
Locked doors could be opened using a lock pick (bought in town) or a key (found in a chest or monster).

**Comment by tgruby** [comment]
oh, that's a good idea.  locked doors should contain extra treasures.

**Comment by tgruby** [comment]
I think there should be "skeleton keys" only dropped by skeletons.  :)

**Comment by tgruby** [comment]
re-reading this.  Basically the next level would require a skeleton key.  so I like the idea even more, it isn't about treasure, it is about getting to the next level.

**Comment by tgruby** [comment]
done
